export const SET_SYMBOLS = {
  "Base Set": "https://images.pokemontcg.io/base1/symbol.png",
  Jungle: "https://images.pokemontcg.io/base2/symbol.png",
  Fossil: "https://images.pokemontcg.io/base3/symbol.png",
  "Base Set 2": "https://images.pokemontcg.io/base4/symbol.png",
  "Team Rocket": "https://images.pokemontcg.io/base5/symbol.png",
  "Black Star Promo": "https://images.pokemontcg.io/basep/symbol.png",
  "Gym Heroes": "https://images.pokemontcg.io/gym1/symbol.png",
  "Gym Challenge": "https://images.pokemontcg.io/gym2/symbol.png",
  "Neo Genesis": "https://images.pokemontcg.io/neo1/symbol.png",
  "Neo Discovery": "https://images.pokemontcg.io/neo2/symbol.png",
  "Neo Revelation": "https://images.pokemontcg.io/neo3/symbol.png",
  "Neo Destiny": "https://images.pokemontcg.io/neo4/symbol.png",
  "Legendary Collection": "https://images.pokemontcg.io/base6/symbol.png",
  "Expedition Base Set": "https://images.pokemontcg.io/ecard1/symbol.png",
  Aquapolis: "https://images.pokemontcg.io/ecard2/symbol.png",
  Skyridge: "https://images.pokemontcg.io/ecard3/symbol.png",
  "Ruby & Sapphire": "https://images.pokemontcg.io/ex1/symbol.png",
  Sandstorm: "https://images.pokemontcg.io/ex2/symbol.png",
  Dragon: "https://images.pokemontcg.io/ex3/symbol.png",
  "Team Magma vs Team Aqua": "https://images.pokemontcg.io/ex4/symbol.png",
  "Hidden Legends": "https://images.pokemontcg.io/ex5/symbol.png",
  "FireRed & LeafGreen": "https://images.pokemontcg.io/ex6/symbol.png",
  "Team Rocket Returns": "https://images.pokemontcg.io/ex7/symbol.png",
  Deoxys: "https://images.pokemontcg.io/ex8/symbol.png",
  Emerald: "https://images.pokemontcg.io/ex9/symbol.png",
  "Unseen Forces": "https://images.pokemontcg.io/ex10/symbol.png",
  "Delta Species": "https://images.pokemontcg.io/ex11/symbol.png",
  "Legend Maker": "https://images.pokemontcg.io/ex12/symbol.png",
  "Holon Phantoms": "https://images.pokemontcg.io/ex13/symbol.png",
  "Crystal Guardians": "https://images.pokemontcg.io/ex14/symbol.png",
  "Dragon Frontiers": "https://images.pokemontcg.io/ex15/symbol.png",
  "Power Keepers": "https://images.pokemontcg.io/ex16/symbol.png",
  "POP Series 1": "https://images.pokemontcg.io/pop1/symbol.png",
  "POP Series 2": "https://images.pokemontcg.io/pop2/symbol.png",
  "POP Series 3": "https://images.pokemontcg.io/pop3/symbol.png",
  "POP Series 4": "https://images.pokemontcg.io/pop4/symbol.png",
  "POP Series 5": "https://images.pokemontcg.io/pop5/symbol.png",
  "POP Series 6": "https://images.pokemontcg.io/pop6/symbol.png",
  "POP Series 7": "https://images.pokemontcg.io/pop7/symbol.png",
  "POP Series 8": "https://images.pokemontcg.io/pop8/symbol.png",
  "POP Series 9": "https://images.pokemontcg.io/pop9/symbol.png",
  "Diamond & Pearl": "https://images.pokemontcg.io/dp1/symbol.png",
  "Mysterious Treasures": "https://images.pokemontcg.io/dp2/symbol.png",
  "Secret Wonders": "https://images.pokemontcg.io/dp3/symbol.png",
  "Great Encounters": "https://images.pokemontcg.io/dp4/symbol.png",
  "Majestic Dawn": "https://images.pokemontcg.io/dp5/symbol.png",
  "Legends Awakened": "https://images.pokemontcg.io/dp6/symbol.png",
  Stormfront: "https://images.pokemontcg.io/dp7/symbol.png",
  Platinum: "https://images.pokemontcg.io/pl1/symbol.png",
  "Rising Rivals": "https://images.pokemontcg.io/pl2/symbol.png",
  "Supreme Victors": "https://images.pokemontcg.io/pl3/symbol.png",
  Arceus: "https://images.pokemontcg.io/pl4/symbol.png",
  "HeartGold & SoulSilver": "https://images.pokemontcg.io/hgss1/symbol.png",
  Unleashed: "https://images.pokemontcg.io/hgss2/symbol.png",
  Undaunted: "https://images.pokemontcg.io/hgss3/symbol.png",
  Triumphant: "https://images.pokemontcg.io/hgss4/symbol.png",
  "Call of Legends": "https://images.pokemontcg.io/col1/symbol.png",
  "Southern Islands": "https://images.pokemontcg.io/si1/symbol.png",
  Rumble: "https://images.pokemontcg.io/ru1/symbol.png",
  "Black & White": "https://images.pokemontcg.io/bw1/symbol.png",
  "Emerging Powers": "https://images.pokemontcg.io/bw2/symbol.png",
  "Noble Victories": "https://images.pokemontcg.io/bw3/symbol.png",
  "Next Destinies": "https://images.pokemontcg.io/bw4/symbol.png",
  "Dark Explorers": "https://images.pokemontcg.io/bw5/symbol.png",
  "Dragons Exalted": "https://images.pokemontcg.io/bw6/symbol.png",
  "Boundaries Crossed": "https://images.pokemontcg.io/bw7/symbol.png",
  "Plasma Storm": "https://images.pokemontcg.io/bw8/symbol.png",
  "Plasma Freeze": "https://images.pokemontcg.io/bw9/symbol.png",
  "Plasma Blast": "https://images.pokemontcg.io/bw10/symbol.png",
  "Legendary Treasures": "https://images.pokemontcg.io/bw11/symbol.png",
  "Best of Game": "https://images.pokemontcg.io/bp/symbol.png",
  "McDonald's Collection 2011": "https://images.pokemontcg.io/mcd11/symbol.png",
  "McDonald's Collection 2012": "https://images.pokemontcg.io/mcd12/symbol.png",
  "McDonald's Collection 2014": "https://images.pokemontcg.io/mcd14/symbol.png",
  "McDonald's Collection 2015": "https://images.pokemontcg.io/mcd15/symbol.png",
  "McDonald's Collection 2016": "https://images.pokemontcg.io/mcd16/symbol.png",
  "McDonald's Collection 2017": "https://images.pokemontcg.io/mcd17/symbol.png",
  "McDonald's Collection 2018": "https://images.pokemontcg.io/mcd18/symbol.png",
  "McDonald's Collection 2019": "https://images.pokemontcg.io/mcd19/symbol.png",
  "McDonald's Collection 2021": "https://images.pokemontcg.io/mcd21/symbol.png",
  "McDonald's Collection 2022": "https://images.pokemontcg.io/mcd22/symbol.png",
  "McDonald's Collection 2023": "https://images.pokemontcg.io/mcd23/symbol.png",
  "McDonald's Collection 2024": "https://images.pokemontcg.io/mcd24/symbol.png",
  "Pokémon Futsal": "https://images.pokemontcg.io/fut20/symbol.png",
  "Kalos Starter Set": "https://images.pokemontcg.io/xy0/symbol.png",
  XY: "https://images.pokemontcg.io/xy1/symbol.png",
  Flashfire: "https://images.pokemontcg.io/xy2/symbol.png",
  "Furious Fists": "https://images.pokemontcg.io/xy3/symbol.png",
  "Phantom Forces": "https://images.pokemontcg.io/xy4/symbol.png",
  "Primal Clash": "https://images.pokemontcg.io/xy5/symbol.png",
  "Roaring Skies": "https://images.pokemontcg.io/xy6/symbol.png",
  "Ancient Origins": "https://images.pokemontcg.io/xy7/symbol.png",
  BREAKthrough: "https://images.pokemontcg.io/xy8/symbol.png",
  BREAKpoint: "https://images.pokemontcg.io/xy9/symbol.png",
  "Fates Collide": "https://images.pokemontcg.io/xy10/symbol.png",
  "Steam Siege": "https://images.pokemontcg.io/xy11/symbol.png",
  Evolutions: "https://images.pokemontcg.io/xy12/symbol.png",
  "Double Crisis": "https://images.pokemontcg.io/dc1/symbol.png",
  Generations: "https://images.pokemontcg.io/g1/symbol.png",
  "Dragon Vault": "https://images.pokemontcg.io/dv1/symbol.png",
  "Sun & Moon": "https://images.pokemontcg.io/sm1/symbol.png",
  "Guardians Rising": "https://images.pokemontcg.io/sm2/symbol.png",
  "Burning Shadows": "https://images.pokemontcg.io/sm3/symbol.png",
  "Crimson Invasion": "https://images.pokemontcg.io/sm4/symbol.png",
  "Ultra Prism": "https://images.pokemontcg.io/sm5/symbol.png",
  "Forbidden Light": "https://images.pokemontcg.io/sm6/symbol.png",
  "Celestial Storm": "https://images.pokemontcg.io/sm7/symbol.png",
  "Lost Thunder": "https://images.pokemontcg.io/sm8/symbol.png",
  "Team Up": "https://images.pokemontcg.io/sm9/symbol.png",
  "Unbroken Bonds": "https://images.pokemontcg.io/sm10/symbol.png",
  "Unified Minds": "https://images.pokemontcg.io/sm11/symbol.png",
  "Cosmic Eclipse": "https://images.pokemontcg.io/sm12/symbol.png",
  "Hidden Fates": "https://images.pokemontcg.io/sm115/symbol.png",
  "Shining Legends": "https://images.pokemontcg.io/sm35/symbol.png",
  "Dragon Majesty": "https://images.pokemontcg.io/sm75/symbol.png",
  "Detective Pikachu": "https://images.pokemontcg.io/det1/symbol.png",
  "Sword & Shield": "https://images.pokemontcg.io/swsh1/symbol.png",
  "Rebel Clash": "https://images.pokemontcg.io/swsh2/symbol.png",
  "Darkness Ablaze": "https://images.pokemontcg.io/swsh3/symbol.png",
  "Champion's Path": "https://images.pokemontcg.io/swsh35/symbol.png",
  "Vivid Voltage": "https://images.pokemontcg.io/swsh4/symbol.png",
  "Shining Fates": "https://images.pokemontcg.io/swsh45/symbol.png",
  "Battle Styles": "https://images.pokemontcg.io/swsh5/symbol.png",
  "Chilling Reign": "https://images.pokemontcg.io/swsh6/symbol.png",
  "Evolving Skies": "https://images.pokemontcg.io/swsh7/symbol.png",
  Celebrations: "https://images.pokemontcg.io/cel25/symbol.png",
  "Fusion Strike": "https://images.pokemontcg.io/swsh8/symbol.png",
  "Brilliant Stars": "https://images.pokemontcg.io/swsh9/symbol.png",
  "Astral Radiance": "https://images.pokemontcg.io/swsh10/symbol.png",
  "Lost Origin": "https://images.pokemontcg.io/swsh11/symbol.png",
  "Silver Tempest": "https://images.pokemontcg.io/swsh12/symbol.png",
  "Pokémon GO": "https://images.pokemontcg.io/pgo/symbol.png",
  "Crown Zenith": "https://images.pokemontcg.io/swsh12pt5/symbol.png",
  "Shiny Vault": "https://images.pokemontcg.io/sma/symbol.png",
  "Hidden Fates": "https://images.pokemontcg.io/sm115/symbol.png",
  "Scarlet & Violet": "https://images.pokemontcg.io/sv1/symbol.png",
  "Paldea Evolved": "https://images.pokemontcg.io/sv2/symbol.png",
  "Obsidian Flames": "https://images.pokemontcg.io/sv3/symbol.png",
  151: "https://images.pokemontcg.io/sv3pt5/symbol.png",
  "Paradox Rift": "https://images.pokemontcg.io/sv4/symbol.png",
  "Paldean Fates": "https://images.pokemontcg.io/sv4pt5/symbol.png",
  "Temporal Forces": "https://images.pokemontcg.io/sv5/symbol.png",
  "Twilight Masquerade": "https://images.pokemontcg.io/sv6/symbol.png",
  "Shrouded Fable": "https://images.pokemontcg.io/sv6pt5/symbol.png",
  "Stellar Crown": "https://images.pokemontcg.io/sv7/symbol.png",
  "Surging Sparks": "https://images.pokemontcg.io/sv8/symbol.png",
  "Prismatic Evolutions": "https://images.pokemontcg.io/sv8pt5/symbol.png",
  "Journey Together": "https://images.pokemontcg.io/sv9/symbol.png",
  "Destined Rivals": "https://images.pokemontcg.io/sv10/symbol.png",
  "Black Bolt": "https://images.pokemontcg.io/zsv10pt5/symbol.png",
  "White Flare": "https://images.pokemontcg.io/rsv10pt5/symbol.png",
  "Mega Evolution": "https://images.pokemontcg.io/me1/symbol.png",
  "Phantasmal Flames": "https://images.pokemontcg.io/me2/symbol.png",
  "Ascended Heroes": "https://images.pokemontcg.io/me2pt5/symbol.png",
};
